name: movil_unistock
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.6
  intl: ^0.18.1
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^9.2.4
  excel: ^4.0.6
  share_plus: ^12.0.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logouni.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
